#include "gistemp_sra.h"
#include <json-glib/json-glib.h>

struct AtmGistempSra {
    AtmGistempEvidence *evidence;
    AtmSraResult *result;
};
static gboolean reject (GError **error, const char *message)
{
    g_set_error_literal (error, ATM_SRA_ERROR, ATM_SRA_ERROR_IDENTITY, message);
    return FALSE;
}
/* Called only with source-reconstructed, validated evidence. */
static AtmSraResult *build_result (const AtmGistempEvidence *e, GError **error)
{
    if (!atm_gistemp_evidence_validate (e, error)) return NULL;
    AtmSraResult *r = atm_sra_result_new (ATM_SRA_ANSWERED);
    const AtmScientificArtifact *first = atm_gistemp_evidence_at (e, 0);
    char *snapshot = g_strdup_printf ("%s@%s#%s", first->repository_id,
                                      first->repository_version, first->snapshot_sha);
    gboolean qualified = atm_sra_qualification_add_repository_snapshot (r, snapshot, error);
    g_free (snapshot);
    if (!qualified ||
        !atm_sra_qualification_add_canonical_obligation (r, ATM_SRA_SCHEMA_ID, error) ||
        !atm_sra_qualification_add_canonical_obligation (r, "atm-gistemp-source-reconstruction/1", error) ||
        !atm_sra_qualification_add_semantic_profile (r, ATM_GISTEMP_EVIDENCE_PROFILE "@1", error) ||
        !atm_sra_qualification_set_numeric_profile (r, "exact_decimal_coefficient_exponent/1", error))
        goto invalid;
    for (guint i = 0; i < atm_gistemp_evidence_count (e); i++)
        if (!atm_sra_qualification_add_evidence_artifact (r, atm_gistemp_evidence_at (e, i), error))
            goto invalid;
    for (guint i = 0; i < 146; i++) {
        const AtmScientificArtifact *a = atm_gistemp_evidence_at (e, i + 4);
        JsonParser *parser = json_parser_new ();
        if (!json_parser_load_from_data (parser, a->payload, -1, error)) {
            g_object_unref (parser);
            goto invalid;
        }
        JsonObject *o = json_node_get_object (json_parser_get_root (parser));
        /* Inputs below are generated by the validated, fixed evidence adapter.
         * Scientific decimal value stays textual; never convert via double. */
        char *value = g_strdup_printf ("%se%s",
            json_object_get_string_member (o, "coefficient"),
            json_object_get_string_member (o, "exponent"));
        AtmSraEstablishedFact *fact = atm_sra_established_fact_new (
            a->logical_source_id, a->artifact_class,
            json_object_get_string_member (o, "subject"),
            json_object_get_string_member (o, "attribute"), value,
            json_object_get_string_member (o, "unit"),
            json_object_get_string_member (o, "dimension"), a->payload);
        g_free (value);
        g_object_unref (parser);
        if (fact == NULL) {
            reject (error, "Cannot construct source observation fact.");
            goto invalid;
        }
        gboolean supported = TRUE;
        for (guint j = 0; j < 5; j++) {
            if (!atm_sra_fact_add_support (fact, atm_gistemp_evidence_point_support (e, i, j), error)) {
                supported = FALSE;
                break;
            }
        }
        if (!supported || !atm_sra_result_add_fact (r, fact, error)) {
            atm_sra_established_fact_free (fact);
            goto invalid;
        }
    }
    if (!atm_sra_result_add_limitation (r, "Pinned processed observations; raw NASA processing not reproduced.", error) ||
        !atm_sra_result_add_limitation (r, "Source-specific annual observations only; not a World3 pollution trajectory.", error) ||
        !atm_sra_result_add_limitation (r, "No VerifiedSeries, rendering or general missing-value authority.", error) ||
        !atm_sra_result_finalize (r, error)) goto invalid;
    return r;
invalid:
    atm_sra_result_free (r);
    return NULL;
}
void atm_gistemp_sra_free (AtmGistempSra *s)
{
    if (s == NULL) return;
    atm_gistemp_evidence_free (s->evidence);
    atm_sra_result_free (s->result);
    g_free (s);
}
gboolean atm_gistemp_sra_new (const AtmGistempAdmission *admission,
    AtmGistempSra **out, GError **error)
{
    if (admission == NULL || out == NULL || *out != NULL)
        return reject (error, "Invalid source SRA arguments.");
    AtmGistempSra *s = g_new0 (AtmGistempSra, 1);
    if (!atm_gistemp_evidence_new (admission, &s->evidence, error)) goto invalid;
    s->result = build_result (s->evidence, error);
    if (s->result == NULL) goto invalid;
    *out = s;
    return TRUE;
invalid:
    atm_gistemp_sra_free (s);
    return FALSE;
}
gboolean atm_gistemp_sra_validate (const AtmGistempSra *s, GError **error)
{
    if (s == NULL) return reject (error, "Missing source SRA.");
    if (!atm_sra_result_validate (s->result, error)) return FALSE;
    AtmSraResult *expected = build_result (s->evidence, error);
    if (expected == NULL) return FALSE;
    gboolean matches = g_strcmp0 (s->result->qualification->scientific_content_id,
                                  expected->qualification->scientific_content_id) == 0 &&
                       g_strcmp0 (s->result->qualification->qualified_artifact_id,
                                  expected->qualification->qualified_artifact_id) == 0;
    atm_sra_result_free (expected);
    return matches || reject (error, "Finalized SRA disagrees with reconstructed source observations.");
}
const AtmSraResult *atm_gistemp_sra_result (const AtmGistempSra *s)
{ return s != NULL ? s->result : NULL; }
