name: Flatpak

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: AskTheModel.flatpak
          manifest-path: io.github.laurentiustaicu.ask_the_model.yml
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: flatpak-builder-${{ github.sha }}
